name: "Run unit tests"
on:
  push:

jobs:
  qc-and-test:
    name: "QC and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: pip install -e .[all]

      - name: Unit tests [pytest]
        run: |
          pytest --cov=seafile_downloader --cov-report term-missing
          coverage report --format=markdown -m >> $GITHUB_STEP_SUMMARY

      - name: QC [ruff]
        if: ${{!cancelled()}}
        run: ruff check seafile_downloader
